---

# NOTE: Since Ansible uses Python on the backend, all boolean values are capitalized when being
# rendered (which is not valid TOML). To get around this, make sure you quote any boolean values
# (true -> "true") to ensure correct formatting (for template variables).

# InfluxDB configuration file options
influxdb_configuration_dir: /etc/influxdb
influxdb_disable_reporting: "true"


## Create database for telegraf
influxdb_telegraf_setup: yes
influxdb_telegraf_hostname: localhost
influxdb_telegraf_db_name: telegraf

## Meta Settings
influxdb_meta_dir: /var/lib/influxdb/meta

## Data Settings
influxdb_data_dir: /var/lib/influxdb

## Retention Settings
influxdb_retention_enabled: "true"

### GRAFANA ###
grafana_repo_channel: stable
grafana_repo_base_url: "https://packagecloud.io/grafana/{{ grafana_repo_channel }}"
grafana_repo_yum_baseurl: "{{ grafana_repo_base_url }}/el/$releasever/$basearch"


### TELEGRAF ###
telegraf_influxdb_url: "http://{{ influxdb_telegraf_hostname }}:8086"
telegraf_influxdb_db_name: "{{ influxdb_telegraf_db_name }}"
