---
- name: Install any necessary dependencies for influxdb
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - python-pip

- name: Install python package dependencies for influxdb
  become: true
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - influxdb

- name: Install InfluxDB packages
  yum: 
    name: influxdb
    state: present
